"""Начальные задания, загружаются в БД при первом старте."""

SEED_TASKS = [
    # ================= Фишинг =================
    {
        "title": "Ловись, рыбка!",
        "description": "Поймай опасные сообщения-рыбки и спаси безопасные",
        "instructions": "Перетащи каждое сообщение в правильный аквариум: 🟢 Безопасное или 🔴 Фишинг.",
        "topic": "phishing",
        "task_type": "dragdrop",
        "age_groups": ["junior", "middle"],
        "points": 10,
        "emoji": "🎣",
        "color": "#FF7043",
        "order": 1,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "safe", "label": "Безопасно", "emoji": "🟢"},
                {"id": "danger", "label": "Фишинг!", "emoji": "🔴"},
            ],
            "items": [
                {"id": "p1", "text": "Мама пишет: «Ужин готов, иди кушать!»", "section": "safe", "emoji": "🏠"},
                {"id": "p2", "text": "Незнакомец пишет: «Отправь мне пароль — выиграешь приз!»", "section": "danger", "emoji": "🎁"},
                {"id": "p3", "text": "Учитель пишет: «Завтра контрольная по математике»", "section": "safe", "emoji": "📚"},
                {"id": "p4", "text": "Сайт просит: «Введи номер карты, чтобы получить подарок»", "section": "danger", "emoji": "💳"},
                {"id": "p5", "text": "Друг пишет: «Посмотри, какой смешной кот!» (это ссылка, но друг проверил её)", "section": "safe", "emoji": "🐱"},
                {"id": "p6", "text": "Письмо: «Ты выиграл телефон! Нажми на ссылку и введи свои данные»", "section": "danger", "emoji": "📱"},
            ],
        },
    },
    {
        "title": "Хитрый фишер",
        "description": "Вычисли письма от обманщиков",
        "instructions": "Для каждого вопроса выбери правильный ответ.",
        "topic": "phishing",
        "task_type": "quiz",
        "age_groups": ["middle", "senior"],
        "points": 15,
        "emoji": "🕵️",
        "color": "#FF7043",
        "order": 2,
        "forbidden_groups": [],
        "content": {
            "questions": [
                {
                    "id": "fq1",
                    "question": "Письмо обещает «миллион за 5 минут» и просит прислать данные карты. Что делать?",
                    "options": [
                        "Быстро отправить данные — вдруг правда!",
                        "Не отвечать и рассказать взрослым",
                        "Ответить и попросить больше",
                    ],
                    "correct": 1,
                    "explanation": "Слишком хорошие предложения почти всегда обман. Никогда не отправляй свои данные.",
                },
                {
                    "id": "fq2",
                    "question": "Адрес отправителя выглядит так: «bank@secure-mail.ru1». Как понять, что это фишинг?",
                    "options": [
                        "Никак, это точно банк",
                        "Нужно нажать на ссылку и проверить",
                        "Обрати внимание на странный адрес и лучше спросить взрослых",
                    ],
                    "correct": 2,
                    "explanation": "Мошенники подделывают адреса. Странный адрес — повод быть осторожным.",
                },
                {
                    "id": "fq3",
                    "question": "Друг прислал файл «фото.exe» и просит открыть. Что правильно?",
                    "options": [
                        "Открыть сразу",
                        "Спросить, что это, и не открывать файлы с .exe",
                        "Открыть и потом рассказать",
                    ],
                    "correct": 1,
                    "explanation": "Файлы с расширением .exe — программы, а не картинки. Они могут быть опасны.",
                },
            ],
        },
    },
    # ================= Кибербуллинг =================
    {
        "title": "Злой робот и добрый робот",
        "description": "Раздели сообщения на добрые и злые",
        "instructions": "Разложи сообщения по корзинам: добрые слова и обидные слова.",
        "topic": "cyberbullying",
        "task_type": "sort",
        "age_groups": ["junior", "middle"],
        "points": 10,
        "emoji": "🤖",
        "color": "#42A5F5",
        "order": 3,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "kind", "label": "Добрые", "emoji": "😊"},
                {"id": "mean", "label": "Обидные", "emoji": "😠"},
            ],
            "items": [
                {"id": "b1", "text": "«Ты классно рисуешь!»", "section": "kind", "emoji": "🎨"},
                {"id": "b2", "text": "«Ты глупый, уходи отсюда»", "section": "mean", "emoji": "💢"},
                {"id": "b3", "text": "«Давай играть вместе»", "section": "kind", "emoji": "🎮"},
                {"id": "b4", "text": "«Над тобой все смеются»", "section": "mean", "emoji": "😈"},
                {"id": "b5", "text": "«Спасибо за помощь!»", "section": "kind", "emoji": "🙏"},
                {"id": "b6", "text": "«Никто с тобой не дружит»", "section": "mean", "emoji": "🗯️"},
            ],
        },
    },
    {
        "title": "Что делать, если обижают",
        "description": "Выбери правильные действия в сложной ситуации",
        "instructions": "Прочитай ситуацию и выбери, как поступить правильно.",
        "topic": "cyberbullying",
        "task_type": "scenario",
        "age_groups": ["middle", "senior"],
        "points": 15,
        "emoji": "🦸",
        "color": "#42A5F5",
        "order": 4,
        "forbidden_groups": [],
        "content": {
            "scenarios": [
                {
                    "id": "cb1",
                    "title": "Обидные комментарии",
                    "description": "Кто-то пишет тебе злые сообщения в чате игры каждый день.",
                    "options": [
                        "Отвечать тем же и обзываться",
                        "Не отвечать, заблокировать обидчика и рассказать взрослым",
                        "Удалить аккаунт и никому не говорить",
                    ],
                    "correct": 1,
                    "explanation": "Лучше не отвечать обидчику — так он перестаёт получать внимание. Блокировка и разговор со взрослым защитят тебя.",
                },
                {
                    "id": "cb2",
                    "title": "Чужое фото",
                    "description": "Кто-то выложил твою фотографию без разрешения и надписал её смешно.",
                    "options": [
                        "Не обращать внимания",
                        "Сделать фото и выложить в ответ",
                        "Попросить удалить, сохранить скриншот и сообщить взрослым/наставнику",
                    ],
                    "correct": 2,
                    "explanation": "Публикация фото без разрешения — нарушение. Скриншот — доказательство, а взрослые помогут всё удалить.",
                },
            ],
        },
    },
    # ================= Пароли =================
    {
        "title": "Крепкий замок",
        "description": "Собери пароль, который сложно взломать",
        "instructions": "Перетащи части в замок, чтобы собрать сильный пароль.",
        "topic": "passwords",
        "task_type": "dragdrop",
        "age_groups": ["junior", "middle"],
        "points": 10,
        "emoji": "🔑",
        "color": "#FFCA28",
        "order": 5,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "strong", "label": "Сильный пароль", "emoji": "🔐"},
                {"id": "weak", "label": "Слабый пароль", "emoji": "🔓"},
            ],
            "items": [
                {"id": "pw1", "text": "12345", "section": "weak", "emoji": "🔢"},
                {"id": "pw2", "text": "Kotik2025!Sunny", "section": "strong", "emoji": "☀️"},
                {"id": "pw3", "text": "пароль", "section": "weak", "emoji": "🆗"},
                {"id": "pw4", "text": "R2D2&Star-Wars9", "section": "strong", "emoji": "🤖"},
                {"id": "pw5", "text": "qwerty", "section": "weak", "emoji": "⌨️"},
                {"id": "pw6", "text": "MoyaKoshka#2026!", "section": "strong", "emoji": "🐱"},
            ],
        },
    },
    {
        "title": "Правда или ложь: пароли",
        "description": "Проверь, что ты знаешь о паролях",
        "instructions": "Отметь, правда это или ложь.",
        "topic": "passwords",
        "task_type": "true_false",
        "age_groups": ["middle", "senior"],
        "points": 10,
        "emoji": "⚖️",
        "color": "#FFCA28",
        "order": 6,
        "forbidden_groups": [],
        "content": {
            "statements": [
                {
                    "id": "pt1",
                    "statement": "Один и тот же пароль хорошо использовать везде.",
                    "is_true": False,
                    "explanation": "Если один пароль украдут, злоумышленник попадёт во все твои аккаунты.",
                },
                {
                    "id": "pt2",
                    "statement": "Пароль с буквами, цифрами и символами сложнее взломать.",
                    "is_true": True,
                    "explanation": "Чем больше разных символов — тем труднее пароль угадать.",
                },
                {
                    "id": "pt3",
                    "statement": "Можно сообщать пароль лучшему другу.",
                    "is_true": False,
                    "explanation": "Пароль — это секрет только для тебя. Даже лучшие друзья не должны его знать.",
                },
                {
                    "id": "pt4",
                    "statement": "День рождения — хороший пароль.",
                    "is_true": False,
                    "explanation": "Дату рождения легко узнать и легко угадать.",
                },
            ],
        },
    },
    # ================= Вирусы =================
    {
        "title": "Мусорный бак для вирусов",
        "description": "Выброси подозрительные файлы",
        "instructions": "Определи, что опасно, а что безопасно открывать.",
        "topic": "viruses",
        "task_type": "sort",
        "age_groups": ["junior", "middle"],
        "points": 10,
        "emoji": "🦠",
        "color": "#66BB6A",
        "order": 7,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "virus", "label": "Опасно!", "emoji": "☠️"},
                {"id": "safe", "label": "Безопасно", "emoji": "✅"},
            ],
            "items": [
                {"id": "v1", "text": "Файл «бесплатные-игры.exe» от незнакомца", "section": "virus", "emoji": "🎮"},
                {"id": "v2", "text": "Ссылка от друга на проверенный мультик", "section": "safe", "emoji": "🍿"},
                {"id": "v3", "text": "Всплывающее окно «Твой компьютер сломан, скачай это!»", "section": "virus", "emoji": "🪟"},
                {"id": "v4", "text": "Файл с картинкой от одноклассницы (обычное фото)", "section": "safe", "emoji": "🖼️"},
                {"id": "v5", "text": "Файл «антивирус-бесплатно» с сайта-незнакомца", "section": "virus", "emoji": "🛡️"},
            ],
        },
    },
    {
        "title": "Вирусы: что это?",
        "description": "Ответь на вопросы про вредоносные программы",
        "instructions": "Выбери правильный ответ в каждом вопросе.",
        "topic": "viruses",
        "task_type": "quiz",
        "age_groups": ["middle", "senior"],
        "points": 15,
        "emoji": "🔬",
        "color": "#66BB6A",
        "order": 8,
        "forbidden_groups": [],
        "content": {
            "questions": [
                {
                    "id": "vq1",
                    "question": "Что помогает защитить компьютер от вирусов?",
                    "options": [
                        "Включать компьютер и выключать его",
                        "Антивирусная программа и обновления",
                        "Рисовать на экране",
                    ],
                    "correct": 1,
                    "explanation": "Антивирус проверяет файлы, а обновления закрывают дырки в программах.",
                },
                {
                    "id": "vq2",
                    "question": "Если на экране появилось окно «Вы выиграли!» и кнопка «Узнать», что делать?",
                    "options": [
                        "Нажать скорее, пока не пропало",
                        "Спросить взрослых и не нажимать",
                        "Нажать два раза",
                    ],
                    "correct": 1,
                    "explanation": "Такие окна часто ведут на опасные сайты. Лучше закрыть и рассказать взрослым.",
                },
                {
                    "id": "vq3",
                    "question": "Почему нельзя открывать вложения в письмах от незнакомцев?",
                    "options": [
                        "Они могут содержать вирус",
                        "Они очень скучные",
                        "Они занимают место",
                    ],
                    "correct": 0,
                    "explanation": "Вредоносные файлы часто прячутся именно во вложениях.",
                },
            ],
        },
    },
    # ================= Личные данные =================
    {
        "title": "Что можно говорить?",
        "description": "Раздели данные на личные и обычные",
        "instructions": "Перетащи данные: что можно сообщать в интернете, а что нельзя.",
        "topic": "privacy",
        "task_type": "dragdrop",
        "age_groups": ["junior", "middle"],
        "points": 10,
        "emoji": "🔒",
        "color": "#AB47BC",
        "order": 9,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "private", "label": "Личное — нельзя!", "emoji": "🙊"},
                {"id": "ok", "label": "Можно", "emoji": "🙂"},
            ],
            "items": [
                {"id": "pr1", "text": "Домашний адрес", "section": "private", "emoji": "🏠"},
                {"id": "pr2", "text": "Любимый цвет", "section": "ok", "emoji": "🎨"},
                {"id": "pr3", "text": "Пароль от почты", "section": "private", "emoji": "🔐"},
                {"id": "pr4", "text": "Имя (без фамилии и адреса)", "section": "ok", "emoji": "👧"},
                {"id": "pr5", "text": "Номер телефона", "section": "private", "emoji": "📞"},
                {"id": "pr6", "text": "Любимая еда", "section": "ok", "emoji": "🍕"},
            ],
        },
    },
    {
        "title": "Цифровая тайна",
        "description": "Правда или ложь о личных данных",
        "instructions": "Реши, правда это или ложь.",
        "topic": "privacy",
        "task_type": "true_false",
        "age_groups": ["middle", "senior"],
        "points": 10,
        "emoji": "🤫",
        "color": "#AB47BC",
        "order": 10,
        "forbidden_groups": [],
        "content": {
            "statements": [
                {
                    "id": "prt1",
                    "statement": "Данные, которые ты один раз выложил в сеть, могут остаться там навсегда.",
                    "is_true": True,
                    "explanation": "Даже после удаления копии могут остаться на других устройствах.",
                },
                {
                    "id": "prt2",
                    "statement": "Незнакомцу в игре можно назвать свой адрес, если он обещал конфеты.",
                    "is_true": False,
                    "explanation": "Никогда не сообщай адрес, телефон и пароли незнакомым людям.",
                },
                {
                    "id": "prt3",
                    "statement": "Фотографии могут рассказать о тебе больше, чем кажется.",
                    "is_true": True,
                    "explanation": "По фото можно узнать место, школу и другие детали.",
                },
                {
                    "id": "prt4",
                    "statement": "Если сайт просит твои данные «для игры», можно их дать.",
                    "is_true": False,
                    "explanation": "Сайты не должны просить личные данные у детей. Спроси взрослых.",
                },
            ],
        },
    },
    {
        "title": "Ты — супергерой безопасности",
        "description": "Реши, как поступит настоящий герой",
        "instructions": "Выбери действие супергероя в каждой ситуации.",
        "topic": "privacy",
        "task_type": "scenario",
        "age_groups": ["senior"],
        "points": 15,
        "emoji": "🦸‍♂️",
        "color": "#AB47BC",
        "order": 11,
        "forbidden_groups": [],
        "content": {
            "scenarios": [
                {
                    "id": "sg1",
                    "title": "Настройки приватности",
                    "description": "Ты зарегистрировался в новой соцсети. Что сделать в первую очередь?",
                    "options": [
                        "Сразу опубликовать свой адрес",
                        "Открыть настройки приватности и ограничить доступ к профилю",
                        "Ничего не менять",
                    ],
                    "correct": 1,
                    "explanation": "Настройки приватности защищают твои данные от посторонних.",
                },
                {
                    "id": "sg2",
                    "title": "Странное фото",
                    "description": "Одноклассник выложил фото, где видно табличку с названием твоей школы.",
                    "options": [
                        "Оставить всё как есть",
                        "Попросить удалить фото, потому что это личная информация",
                        "Выложить его фото в ответ",
                    ],
                    "correct": 1,
                    "explanation": "Место учёбы — личная информация. Вежливо попроси удалить и расскажи взрослым.",
                },
            ],
        },
    },
    # ================= Старшая группа — фишинг =================
    {
        "title": "Проверь ссылку",
        "description": "Вычисли подозрительные ссылки и письма",
        "instructions": "Разложи письма: доверенные и подозрительные.",
        "topic": "phishing",
        "task_type": "sort",
        "age_groups": ["senior"],
        "points": 15,
        "emoji": "🧭",
        "color": "#FF7043",
        "order": 12,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "trust", "label": "Доверяю", "emoji": "👍"},
                {"id": "suspect", "label": "Подозрительно", "emoji": "🚩"},
            ],
            "items": [
                {"id": "l1", "text": "Письмо от школы: «Родительское собрание в субботу»", "section": "trust", "emoji": "🏫"},
                {"id": "l2", "text": "«Срочно! Подтверди пароль, иначе аккаунт удалят»", "section": "suspect", "emoji": "⚠️"},
                {"id": "l3", "text": "Ошибка в адресе: «vkontakte» вместо «vk.com»", "section": "suspect", "emoji": "🔗"},
                {"id": "l4", "text": "Уведомление из официального приложения банка", "section": "trust", "emoji": "🏦"},
                {"id": "l5", "text": "«Ты выиграл iPhone — введи данные карты»", "section": "suspect", "emoji": "📱"},
            ],
        },
    },
    # ================= Средняя группа — сценарии фишинга =================
    {
        "title": "Ловушка для хакера",
        "description": "Помоги герою не попасться в ловушку",
        "instructions": "Выбери, как поступить правильно в каждой ситуации.",
        "topic": "phishing",
        "task_type": "scenario",
        "age_groups": ["middle", "senior"],
        "points": 15,
        "emoji": "🥷",
        "color": "#FF7043",
        "order": 13,
        "forbidden_groups": [],
        "content": {
            "scenarios": [
                {
                    "id": "ph1",
                    "title": "Сообщение от «друга»",
                    "description": "Друг пишет: «Пришли мне код из смс, у меня телефон сломался, это срочно!»",
                    "options": [
                        "Отправить код — это же друг!",
                        "Позвонить другу и уточнить, а код никому не отправлять",
                        "Отправить код, но попросить ничего не терять",
                    ],
                    "correct": 1,
                    "explanation": "Мошенники могут взломать аккаунт друга. Коды из смс — это твой секрет, их нельзя пересылать.",
                },
                {
                    "id": "ph2",
                    "title": "QR-код на остановке",
                    "description": "На остановке наклейка: «Сканируй и получи скидку в магазине!»",
                    "options": [
                        "Просканировать и ввести данные",
                        "Не сканировать незнакомые коды",
                        "Просканировать и проверить вручную адрес",
                    ],
                    "correct": 1,
                    "explanation": "Неизвестные QR-коды могут вести на опасные сайты.",
                },
            ],
        },
    },
    # ================= 3D-кубы безопасности =================
    {
        "title": "Волшебный куб безопасности",
        "description": "Поймай кубики и забрось их в правильные зоны",
        "instructions": "Хватай 3D-кубики в центре и перетаскивай их в зоны по бокам: фишинг, пароли, вирусы и другие.",
        "topic": "privacy",
        "task_type": "drag3d",
        "age_groups": ["junior", "middle"],
        "points": 15,
        "emoji": "🧊",
        "color": "#7C4DFF",
        "order": 14,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "phishing", "label": "Фишинг", "icon": "email"},
                {"id": "cyberbullying", "label": "Кибербуллинг", "icon": "shield"},
                {"id": "passwords", "label": "Пароли", "icon": "key"},
                {"id": "viruses", "label": "Вирусы", "icon": "bug"},
                {"id": "privacy", "label": "Личные данные", "icon": "privacy"},
                {"id": "safe", "label": "Безопасные действия", "icon": "safety"},
            ],
            "items": [
                {"id": "3d1", "text": "Код из SMS незнакомцу", "section": "phishing"},
                {"id": "3d2", "text": "Ссылка от неизвестного", "section": "phishing"},
                {"id": "3d3", "text": "Обидные комментарии", "section": "cyberbullying"},
                {"id": "3d4", "text": "Скриншот для взрослых", "section": "cyberbullying"},
                {"id": "3d5", "text": "Пароль 12345", "section": "passwords"},
                {"id": "3d6", "text": "Разный пароль на сайтах", "section": "passwords"},
                {"id": "3d7", "text": "Файл «игры.exe»", "section": "viruses"},
                {"id": "3d8", "text": "Проверка антивирусом", "section": "viruses"},
                {"id": "3d9", "text": "Домашний адрес в чате", "section": "privacy"},
                {"id": "3d10", "text": "Номер телефона чужому", "section": "privacy"},
                {"id": "3d11", "text": "Спросить взрослых", "section": "safe"},
                {"id": "3d12", "text": "Не открывать ссылки", "section": "safe"},
            ],
        },
    },
    {
        "title": "Куб безопасности: мастер",
        "description": "Сложный уровень — больше кубиков и хитрых случаев",
        "instructions": "Перетащи все кубики в правильные зоны. Будь внимателен: некоторые случаи хитрые!",
        "topic": "privacy",
        "task_type": "drag3d",
        "age_groups": ["middle", "senior"],
        "points": 20,
        "emoji": "🔮",
        "color": "#EC407A",
        "order": 15,
        "forbidden_groups": [],
        "content": {
            "sections": [
                {"id": "phishing", "label": "Фишинг", "icon": "email"},
                {"id": "cyberbullying", "label": "Кибербуллинг", "icon": "shield"},
                {"id": "passwords", "label": "Пароли", "icon": "key"},
                {"id": "viruses", "label": "Вирусы", "icon": "bug"},
                {"id": "privacy", "label": "Личные данные", "icon": "privacy"},
                {"id": "safe", "label": "Безопасные действия", "icon": "safety"},
            ],
            "items": [
                {"id": "3m1", "text": "Срочный код из SMS", "section": "phishing"},
                {"id": "3m2", "text": "Подозрительный адрес письма", "section": "phishing"},
                {"id": "3m3", "text": "Подделанный QR-код", "section": "phishing"},
                {"id": "3m4", "text": "Обидное видео в чате", "section": "cyberbullying"},
                {"id": "3m5", "text": "Скрыть профиль от чужих", "section": "cyberbullying"},
                {"id": "3m6", "text": "Один пароль везде", "section": "passwords"},
                {"id": "3m7", "text": "Двухфакторная защита", "section": "passwords"},
                {"id": "3m8", "text": "Вложение от незнакомца", "section": "viruses"},
                {"id": "3m9", "text": "Обновление антивируса", "section": "viruses"},
                {"id": "3m10", "text": "Геометка на фото", "section": "privacy"},
                {"id": "3m11", "text": "Чужое фото без спроса", "section": "privacy"},
                {"id": "3m12", "text": "Не вводить данные карты", "section": "safe"},
                {"id": "3m13", "text": "Сообщить наставнику", "section": "safe"},
                {"id": "3m14", "text": "Блокировать обидчика", "section": "safe"},
            ],
        },
    },
]